### PR TITLE
feature/gwe-14-add-products

### PR DESCRIPTION
**Pull request by joshxfi**
- [x] feat: ui
- [x] feat: upload image
- [x] chore: updated `TwoLayout` horizontal layout `=` breakpoint to `md` from `sm`
- [x] chore: updated `DashNav` to have `extraTab` prop instead of explicitly `addProducts`
- [x] chore: added `DashHeader` component
---
TODO
- [ ] limit variation images to length of variations
- [ ] add data to firebase
- [ ] validate data (min/max length), etc...

image
image

### CODE REVIEW

**Review by princejoogie — CHANGES_REQUESTED** [review]
make variations a list
description and price for each item

**Comment by princejoogie** [comment]
@joshxfi

make sure to have the fields stated in #46 in the UI
each variation will have `description`, `price`, and `image` field

**Comment by joshxfi** [comment]
@princejoogie , I'll make a PR later
image

**Comment by princejoogie** [comment]
@joshxfi shipping options is independent from products

**Comment by princejoogie** [comment]
are the changes done here @joshxfi ?

**Comment by joshxfi** [comment]
@princejoogie on this incoming push, then I'll proceed w/ `gwe-21` #46

**Pull request merged**
