### PR TITLE
feature/gwe-39-seller-and-buyer-chat-UI

### PR DESCRIPTION
**Pull request by zomeru**
Some features like follow, report, emoji are not working yet, but important features are already working pretty fine.
Also added some code to our custom hooks because I was having an issue where the Function Query.where() is being called with undefined data.

no opened
opened
mob-chat
mob-convo

### CODE REVIEW

**Comment by princejoogie** [comment]
can u add a condition to only show timestamp of chat if the previous message is >30min @zomeru

**Comment by princejoogie** [comment]
also send in a video testing the chat feature

**Comment by zomeru** [comment]
Ok master

**Comment by zomeru** [comment]
> also send in a video testing the chat feature



> also send in a video testing the chat feature

**Pull request merged**
