### PR TITLE
func/gwe-54-product-variation

### PR DESCRIPTION
**Pull request by joshxfi**
- updated ui
- minor features
- bug fixes

image

- selected (1st), hover (2nd), default (3rd)
- can select multiple

image

### CODE REVIEW

**Comment by princejoogie** [comment]
what do you mean by "can select multiple"

**Comment by joshxfi** [comment]
@princejoogie users can select multiple variation (that would mean they'd receive x amount of product from variation), or should I only make it one?

**Comment by joshxfi** [comment]
@princejoogie users can select multiple variation (that would mean they'd receive x amount of product from variation), or should I only make it one?

**Comment by joshxfi** [comment]
Oh I think it should only be one, mbmb

**Pull request merged**
